### ISSUE TITLE
App demo/example

### ISSUE THREAD

**Issue by frobert** [wdjungst/redux-devios-axios#1]
Hi, is there any real working app/demo example I could see? Thank you.

**Comment by wdjungst** [comment]
I have plans to do this but I haven't yet.  In the meantime if you have Rails 5 installed you can install this cli globally https://www.npmjs.com/package/create-repack-app and create a project with the full flag.  Example: create-repack-app my-app --full and this will build a rails 5 API with a React front end utilizing this package with user registration and login.

**Comment by frobert** [comment]
Thanks!!

**Comment by wdjungst** [comment]
Added demo
